Repository Sweepic/sweepic-Ai, pull requests merged in 2025-01, with the labels that each got.

#1 [SWEP-26] PR 컨벤션 및 이슈 컨벤션
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/ISSUE_TEMPLATE/버그-해결.md
  .github/ISSUE_TEMPLATE/사용자-정의.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3 [SWEP-27] 깃 컨벤션 및 리드미 파일 초기 설정
  README.md
Labels: 📎 CHORE, :memo: DOCS

#5 [SWEP-32] README.md 파일 수정
  .gitignore
  README.md
Labels: :memo: DOCS

#7 [SWEP-31] google vision api 환경 설정 및 테스트
  .gitignore
  OCR.js
  food.jpeg
  labelDetection.js
  package-lock.json
  package.json
  see.jpeg
Labels: 📎 CHORE

#9 [SWEP-33] OCR API 구현
  OCR.js
  README.md
  ai/controllers/labelController.ts
  ai/controllers/ocrController.ts
  ai/services/labelDetection.ts
  ai/services/ocrService.ts
  food.jpeg
  labelDetection.js
  see.jpeg
Labels: :sparkles: FEAT
